// apps/web/src/features/services/ServicesPage.tsx
import { useEffect, useState } from "react";
import { Box } from "lucide-react";
import { api, type MonitoredService, type SshKey } from "../../lib/api.js";
import { useAuth } from "../../lib/useAuth.js";

export function ServicesPage() {
  const [services, setServices] = useState<MonitoredService[]>([]);
  const [sshKeys, setSshKeys] = useState<SshKey[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState({ name: "", gitRepoUrl: "", sshKeyId: "", branch: "main", dockerImage: "", composePath: "" });
  const { isAdmin } = useAuth();
  const canManage = isAdmin;

  useEffect(() => {
    api.listServices().then((r) => setServices(r.services)).catch((e) => setError(e.message));
    api.listSshKeys().then((r) => setSshKeys(r.keys)).catch(() => {});
  }, []);

  async function handleCreate(ev: React.FormEvent) {
    ev.preventDefault();
    try {
      if (editingId) {
        const svc = await api.updateService(editingId, {
          name: form.name,
          gitRepoUrl: form.gitRepoUrl,
          sshKeyId: form.sshKeyId || null,
          branch: form.branch,
          dockerImage: form.dockerImage.trim() || undefined,
          composePath: form.composePath.trim() || undefined
        });
        setServices((prev) => prev.map((s) => s.id === editingId ? svc : s));
      } else {
        const svc = await api.createService({
          name: form.name,
          gitRepoUrl: form.gitRepoUrl,
          sshKeyId: form.sshKeyId || undefined,
          branch: form.branch,
          dockerImage: form.dockerImage.trim() || undefined,
          composePath: form.composePath.trim() || undefined
        });
        setServices((prev) => [...prev, svc]);
      }
      setShowForm(false);
      setEditingId(null);
      setForm({ name: "", gitRepoUrl: "", sshKeyId: "", branch: "main", dockerImage: "", composePath: "" });
    } catch (e: unknown) {
      setError((e as Error).message);
    }
  }

  function handleEdit(svc: MonitoredService) {
    setForm({
      name: svc.name,
      gitRepoUrl: svc.gitRepoUrl,
      sshKeyId: svc.sshKeyId || "",
      branch: svc.branch,
      dockerImage: svc.dockerImage || "",
      composePath: svc.composePath || ""
    });
    setEditingId(svc.id);
    setShowForm(true);
  }

  async function handleDelete(svc: MonitoredService) {
    if (!window.confirm(`Delete service "${svc.name}"? This will also remove its runs and incidents.`)) {
      return;
    }
    try {
      await api.deleteService(svc.id);
      setServices((prev) => prev.filter((s) => s.id !== svc.id));
      if (editingId === svc.id) {
        setEditingId(null);
        setShowForm(false);
        setForm({ name: "", gitRepoUrl: "", sshKeyId: "", branch: "main", dockerImage: "", composePath: "" });
      }
    } catch (e: unknown) {
      setError((e as Error).message);
    }
  }

  return (
    <section>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1rem" }}>
        <h2 style={{ margin: 0 }}>Monitored Services</h2>
        {canManage && (
          <button onClick={() => { setShowForm(!showForm); setEditingId(null); setForm({ name: "", gitRepoUrl: "", sshKeyId: "", branch: "main", dockerImage: "", composePath: "" }); }} style={primaryBtn}>{showForm ? "Cancel" : "Add Service"}</button>
        )}
      </div>
      {error && <div style={{ color: "var(--color-danger)", marginBottom: "0.5rem" }}>{error}</div>}

      {services.some((s) => !s.sshKeyId) && (
        <div
          role="status"
          style={{
            background: "color-mix(in srgb, var(--color-warning) 12%, var(--color-surface))",
            border: "1px solid var(--color-warning)",
            borderRadius: 8,
            padding: "0.6rem 0.75rem",
            marginBottom: "1rem",
            fontSize: "0.85rem",
            color: "var(--color-text-primary)"
          }}
        >
          <strong>Auto-fix is disabled for some services.</strong> Services without an SSH key can still be
          monitored, but Kaiad cannot push fix commits to their repos. Edit the service and assign an SSH key
          to enable the automated error → fix loop.
        </div>
      )}

      {canManage && showForm && (
        <form onSubmit={handleCreate} style={{ background: "var(--color-surface)", border: "1px solid var(--color-border)", borderRadius: 10, padding: "1rem", marginBottom: "1rem", display: "grid", gap: "0.5rem" }}>
          <label>
            Name
            <input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required style={inputStyle} />
          </label>
          <label>
            Git Repository URL
            <input value={form.gitRepoUrl} onChange={(e) => setForm({ ...form, gitRepoUrl: e.target.value })} required style={inputStyle} placeholder="e.g. git@github.com:acme/app.git" />
          </label>
          <label>
            SSH Key <span style={{ color: "var(--color-text-secondary)", fontSize: "0.8rem" }}>(required if SSH URL)</span>
            <select value={form.sshKeyId} onChange={(e) => setForm({ ...form, sshKeyId: e.target.value })} style={{ ...inputStyle, background: "var(--color-surface)" }}>
              <option value="">— None (HTTPS public) —</option>
              {sshKeys.map((k) => (
                <option key={k.id} value={k.id}>{k.name}</option>
              ))}
            </select>
          </label>
          <label>
            Branch
            <input value={form.branch} onChange={(e) => setForm({ ...form, branch: e.target.value })} required style={inputStyle} />
          </label>
          <label>
            Docker Image <span style={{ color: "var(--color-text-secondary)", fontSize: "0.8rem" }}>(optional)</span>
            <input value={form.dockerImage} onChange={(e) => setForm({ ...form, dockerImage: e.target.value })} placeholder="e.g. myorg/myapp:latest" style={inputStyle} />
          </label>
          <label>
            Compose Path <span style={{ color: "var(--color-text-secondary)", fontSize: "0.8rem" }}>(optional)</span>
            <input value={form.composePath} onChange={(e) => setForm({ ...form, composePath: e.target.value })} placeholder="e.g. docker-compose.yml" style={inputStyle} />
          </label>
          <button type="submit" style={primaryBtn}>{editingId ? "Save Changes" : "Create"}</button>
        </form>
      )}

      {services.length === 0 && !showForm ? (
        <p style={{ color: "var(--color-text-secondary)" }}>No services configured yet.</p>
      ) : (
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              {["Name", "Repository", "Branch", "Agent", "Detectors", "Actions"].map((h) => (
                <th key={h} style={{ textAlign: "left", padding: "0.5rem", borderBottom: "2px solid var(--color-border)", color: "var(--color-text-secondary)", fontSize: "0.8rem" }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {services.map((svc, idx) => (
              <tr key={svc.id || idx}>
                <td style={{ padding: "0.5rem" }}>
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "0.3rem" }}><Box size={14} /> {svc.name}</span>
                </td>
                <td style={{ padding: "0.5rem", fontSize: "0.85rem" }}>{svc.gitRepoUrl}</td>
                <td style={{ padding: "0.5rem", fontSize: "0.85rem" }}>{svc.branch}</td>
                <td style={{ padding: "0.5rem", fontSize: "0.85rem", color: "var(--color-text-secondary)" }}>
                  {svc.agentId ?? "\u2014"}
                </td>
                <td style={{ padding: "0.5rem", fontSize: "0.85rem", color: "var(--color-text-secondary)" }}>
                  Default
                </td>
                <td style={{ padding: "0.5rem", fontSize: "0.85rem" }}>
                  {canManage && (
                    <div style={{ display: "inline-flex", gap: "0.3rem" }}>
                      <button
                        onClick={() => handleEdit(svc)}
                        style={{
                          background: "var(--color-surface)",
                          border: "1px solid var(--color-border)",
                          padding: "0.2rem 0.5rem",
                          borderRadius: 4,
                          cursor: "pointer",
                          fontSize: "0.8rem",
                          color: "var(--color-text-primary)"
                        }}
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => handleDelete(svc)}
                        style={{
                          background: "var(--color-surface)",
                          border: "1px solid var(--color-border)",
                          padding: "0.2rem 0.5rem",
                          borderRadius: 4,
                          cursor: "pointer",
                          fontSize: "0.8rem",
                          color: "var(--color-danger)"
                        }}
                      >
                        Delete
                      </button>
                    </div>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </section>
  );
}

const primaryBtn: React.CSSProperties = {
  background: "var(--color-primary)",
  color: "var(--color-primary-foreground)",
  border: "none",
  borderRadius: 8,
  padding: "0.4rem 0.75rem",
  cursor: "pointer",
  fontSize: "0.85rem"
};

const inputStyle: React.CSSProperties = {
  display: "block",
  width: "100%",
  padding: "0.35rem 0.5rem",
  border: "1px solid var(--color-border)",
  borderRadius: 6,
  marginTop: "0.2rem",
  boxSizing: "border-box"
};

// apps/web/src/features/services/ServicesPage.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { Box } from "lucide-vue-next";
import { api, type Agent, type MonitoredService, type SshKey } from "../../lib/api.js";
import { useAuth } from "../../lib/useAuth.js";

type ServiceForm = {
  name: string;
  gitRepoUrl: string;
  sshKeyId: string;
  branch: string;
  dockerImage: string;
  composePath: string;
  agentIds: string[];
};

const emptyForm = (): ServiceForm => ({
  name: "",
  gitRepoUrl: "",
  sshKeyId: "",
  branch: "main",
  dockerImage: "",
  composePath: "",
  agentIds: []
});

const services = ref<MonitoredService[]>([]);
const sshKeys = ref<SshKey[]>([]);
const agents = ref<Agent[]>([]);
const error = ref<string | null>(null);
const showForm = ref(false);
const editingId = ref<string | null>(null);
const form = reactive<ServiceForm>(emptyForm());

const auth = useAuth();
const canManage = computed(() => auth.value.isAdmin);

onMounted(async () => {
  try {
    const r = await api.listServices();
    services.value = r.services;
  } catch (e: unknown) {
    error.value = (e as Error).message;
  }
  try {
    const r = await api.listSshKeys();
    sshKeys.value = r.keys;
  } catch {
    /* ignore */
  }
  try {
    const r = await api.listAgents();
    agents.value = r.agents;
  } catch {
    /* ignore */
  }
});

function resetForm() {
  Object.assign(form, emptyForm());
}

function toggleAgent(agentId: string) {
  if (form.agentIds.includes(agentId)) {
    form.agentIds = form.agentIds.filter((a) => a !== agentId);
  } else {
    form.agentIds = [...form.agentIds, agentId];
  }
}

async function handleSubmit(ev: Event) {
  ev.preventDefault();
  try {
    if (editingId.value) {
      const svc = await api.updateService(editingId.value, {
        name: form.name,
        gitRepoUrl: form.gitRepoUrl,
        sshKeyId: form.sshKeyId || null,
        branch: form.branch,
        dockerImage: form.dockerImage.trim() || undefined,
        composePath: form.composePath.trim() || undefined,
        agentIds: form.agentIds
      });
      services.value = services.value.map((s) => (s.id === editingId.value ? svc : s));
    } else {
      const svc = await api.createService({
        name: form.name,
        gitRepoUrl: form.gitRepoUrl,
        sshKeyId: form.sshKeyId || undefined,
        branch: form.branch,
        dockerImage: form.dockerImage.trim() || undefined,
        composePath: form.composePath.trim() || undefined,
        agentIds: form.agentIds
      });
      services.value = [...services.value, svc];
    }
    showForm.value = false;
    editingId.value = null;
    resetForm();
  } catch (e: unknown) {
    error.value = (e as Error).message;
  }
}

function handleEdit(svc: MonitoredService) {
  form.name = svc.name;
  form.gitRepoUrl = svc.gitRepoUrl;
  form.sshKeyId = svc.sshKeyId || "";
  form.branch = svc.branch;
  form.dockerImage = svc.dockerImage || "";
  form.composePath = svc.composePath || "";
  form.agentIds = (svc.agents ?? []).map((b) => b.agentId);
  editingId.value = svc.id;
  showForm.value = true;
}

async function handleDelete(svc: MonitoredService) {
  if (!window.confirm(`Delete service "${svc.name}"? This will also remove its runs and incidents.`)) return;
  try {
    await api.deleteService(svc.id);
    services.value = services.value.filter((s) => s.id !== svc.id);
    if (editingId.value === svc.id) {
      editingId.value = null;
      showForm.value = false;
      resetForm();
    }
  } catch (e: unknown) {
    error.value = (e as Error).message;
  }
}

function renderAgents(svc: MonitoredService): string {
  const ids = (svc.agents ?? []).map((b) => b.agentId);
  if (ids.length === 0) return "—";
  return ids.join(", ");
}

const primaryBtn = {
  background: "var(--color-primary)",
  color: "var(--color-primary-foreground)",
  border: "none",
  borderRadius: "8px",
  padding: "0.4rem 0.75rem",
  cursor: "pointer",
  fontSize: "0.85rem"
};

const inputStyle = {
  display: "block",
  width: "100%",
  padding: "0.35rem 0.5rem",
  border: "1px solid var(--color-border)",
  borderRadius: "6px",
  marginTop: "0.2rem",
  boxSizing: "border-box"
} as const;

const noKey = computed(() => services.value.some((s) => !s.sshKeyId));
</script>

<template>
  <section>
    <div :style="{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }">
      <h2 :style="{ margin: 0 }">Monitored Services</h2>
      <button
        v-if="canManage"
        :style="primaryBtn"
        @click="
          showForm = !showForm;
          editingId = null;
          resetForm();
        "
      >
        {{ showForm ? "Cancel" : "Add Service" }}
      </button>
    </div>

    <div v-if="error" :style="{ color: 'var(--color-danger)', marginBottom: '0.5rem' }">{{ error }}</div>

    <div
      v-if="noKey"
      role="status"
      :style="{
        background: 'color-mix(in srgb, var(--color-warning) 12%, var(--color-surface))',
        border: '1px solid var(--color-warning)',
        borderRadius: '8px',
        padding: '0.6rem 0.75rem',
        marginBottom: '1rem',
        fontSize: '0.85rem',
        color: 'var(--color-text-primary)'
      }"
    >
      <strong>Auto-fix is disabled for some services.</strong> Services without an SSH key can still be monitored,
      but Kaiad cannot push fix commits to their repos. Edit the service and assign an SSH key to enable the
      automated error → fix loop.
    </div>

    <form
      v-if="canManage && showForm"
      :style="{
        background: 'var(--color-surface)',
        border: '1px solid var(--color-border)',
        borderRadius: '10px',
        padding: '1rem',
        marginBottom: '1rem',
        display: 'grid',
        gap: '0.5rem'
      }"
      @submit="handleSubmit"
    >
      <label>
        Name
        <input v-model="form.name" required :style="inputStyle" />
      </label>
      <label>
        Git Repository URL
        <input
          v-model="form.gitRepoUrl"
          required
          placeholder="e.g. git@github.com:acme/app.git"
          :style="inputStyle"
        />
      </label>
      <label>
        SSH Key
        <span :style="{ color: 'var(--color-text-secondary)', fontSize: '0.8rem' }">(required if SSH URL)</span>
        <select v-model="form.sshKeyId" :style="{ ...inputStyle, background: 'var(--color-surface)' }">
          <option value="">— None (HTTPS public) —</option>
          <option v-for="k in sshKeys" :key="k.id" :value="k.id">{{ k.name }}</option>
        </select>
      </label>
      <label>
        Branch
        <input v-model="form.branch" required :style="inputStyle" />
      </label>
      <label>
        Docker Image
        <span :style="{ color: 'var(--color-text-secondary)', fontSize: '0.8rem' }">(optional)</span>
        <input v-model="form.dockerImage" placeholder="e.g. myorg/myapp:latest" :style="inputStyle" />
      </label>
      <label>
        Compose Path
        <span :style="{ color: 'var(--color-text-secondary)', fontSize: '0.8rem' }">(optional)</span>
        <input v-model="form.composePath" placeholder="e.g. docker-compose.yml" :style="inputStyle" />
      </label>
      <fieldset
        :style="{
          border: '1px solid var(--color-border)',
          borderRadius: '6px',
          padding: '0.5rem 0.75rem'
        }"
      >
        <legend :style="{ padding: '0 0.4rem', fontSize: '0.8rem', color: 'var(--color-text-secondary)' }">
          Bound agents <span>(many-to-many; pick zero or more)</span>
        </legend>
        <p
          v-if="agents.length === 0"
          :style="{ margin: 0, color: 'var(--color-text-secondary)', fontSize: '0.82rem' }"
        >
          No agents enrolled yet. Bind agents from the Agents page after they appear.
        </p>
        <div v-else :style="{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem 1rem' }">
          <label
            v-for="a in agents"
            :key="a.id"
            :style="{ display: 'inline-flex', gap: '0.3rem', alignItems: 'center', fontSize: '0.85rem' }"
          >
            <input
              type="checkbox"
              :checked="form.agentIds.includes(a.id)"
              @change="toggleAgent(a.id)"
            />
            {{ a.name?.trim() || a.id }}
          </label>
        </div>
      </fieldset>
      <button type="submit" :style="primaryBtn">{{ editingId ? "Save Changes" : "Create" }}</button>
    </form>

    <p v-if="services.length === 0 && !showForm" :style="{ color: 'var(--color-text-secondary)' }">
      No services configured yet.
    </p>

    <table v-else :style="{ width: '100%', borderCollapse: 'collapse' }">
      <thead>
        <tr>
          <th
            v-for="h in ['Name', 'Repository', 'Branch', 'Agents', 'Detectors', 'Actions']"
            :key="h"
            :style="{
              textAlign: 'left',
              padding: '0.5rem',
              borderBottom: '2px solid var(--color-border)',
              color: 'var(--color-text-secondary)',
              fontSize: '0.8rem'
            }"
          >
            {{ h }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(svc, idx) in services" :key="svc.id || idx">
          <td :style="{ padding: '0.5rem' }">
            <span :style="{ display: 'inline-flex', alignItems: 'center', gap: '0.3rem' }">
              <Box :size="14" /> {{ svc.name }}
            </span>
          </td>
          <td :style="{ padding: '0.5rem', fontSize: '0.85rem' }">{{ svc.gitRepoUrl }}</td>
          <td :style="{ padding: '0.5rem', fontSize: '0.85rem' }">{{ svc.branch }}</td>
          <td :style="{ padding: '0.5rem', fontSize: '0.85rem', color: 'var(--color-text-secondary)' }">
            {{ renderAgents(svc) }}
          </td>
          <td :style="{ padding: '0.5rem', fontSize: '0.85rem', color: 'var(--color-text-secondary)' }">Default</td>
          <td :style="{ padding: '0.5rem', fontSize: '0.85rem' }">
            <div v-if="canManage" :style="{ display: 'inline-flex', gap: '0.3rem' }">
              <button
                :style="{
                  background: 'var(--color-surface)',
                  border: '1px solid var(--color-border)',
                  padding: '0.2rem 0.5rem',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '0.8rem',
                  color: 'var(--color-text-primary)'
                }"
                @click="handleEdit(svc)"
              >Edit</button>
              <button
                :style="{
                  background: 'var(--color-surface)',
                  border: '1px solid var(--color-border)',
                  padding: '0.2rem 0.5rem',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '0.8rem',
                  color: 'var(--color-danger)'
                }"
                @click="handleDelete(svc)"
              >Delete</button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </section>
</template>
