// apps/web/src/components/Button.vue
<script setup lang="ts">
import { computed } from "vue";
import "./components.css";

const props = withDefaults(
  defineProps<{
    variant?: "primary" | "secondary" | "danger" | "ghost";
    size?: "sm" | "md";
    loading?: boolean;
    disabled?: boolean;
    type?: "button" | "submit" | "reset";
    className?: string;
  }>(),
  { variant: "primary", size: "md", loading: false, disabled: false, type: "button" }
);

const cls = computed(
  () => `sm-btn sm-btn--${props.variant} sm-btn--${props.size}${props.className ? ` ${props.className}` : ""}`
);
</script>

<template>
  <button
    :type="type"
    :class="cls"
    :disabled="disabled || loading"
    :aria-busy="loading || undefined"
  >
    <template v-if="loading">Loading…</template>
    <slot v-else />
  </button>
</template>

// apps/web/src/components/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from "react";
import "./components.css";

type ButtonVariant = "primary" | "secondary" | "danger" | "ghost";
type ButtonSize = "sm" | "md";

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  children: ReactNode;
}

export function Button({
  variant = "primary",
  size = "md",
  loading = false,
  disabled,
  children,
  className,
  ...rest
}: ButtonProps) {
  return (
    <button
      className={`sm-btn sm-btn--${variant} sm-btn--${size}${className ? ` ${className}` : ""}`}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      {...rest}
    >
      {loading ? "Loading…" : children}
    </button>
  );
}
