// apps/web/src/components/Card.vue
<script setup lang="ts">
import { computed, type CSSProperties } from "vue";
import "./components.css";

const props = defineProps<{
  title?: string;
  className?: string;
  style?: CSSProperties;
}>();

const cls = computed(() => `sm-card${props.className ? ` ${props.className}` : ""}`);
</script>

<template>
  <div :class="cls" :style="style">
    <div v-if="title || $slots.actions" class="sm-card__header">
      <h3 v-if="title" class="sm-card__title">{{ title }}</h3>
      <div v-if="$slots.actions"><slot name="actions" /></div>
    </div>
    <slot />
  </div>
</template>

// apps/web/src/components/Card.tsx
import type { ReactNode } from "react";
import "./components.css";

interface CardProps {
  title?: string;
  actions?: ReactNode;
  children: ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export function Card({ title, actions, children, className, style }: CardProps) {
  return (
    <div className={`sm-card${className ? ` ${className}` : ""}`} style={style}>
      {(title || actions) && (
        <div className="sm-card__header">
          {title && <h3 className="sm-card__title">{title}</h3>}
          {actions && <div>{actions}</div>}
        </div>
      )}
      {children}
    </div>
  );
}
