// apps/web/src/components/Table.tsx
import type { ReactNode } from "react";
import "./components.css";

export interface Column<T> {
  key: string;
  label: string;
  render?: (row: T) => ReactNode;
}

interface TableProps<T> {
  columns: Column<T>[];
  rows: T[];
  emptyMessage?: string;
  rowKey?: (row: T) => string;
}

export function Table<T>({ columns, rows, emptyMessage = "No data.", rowKey }: TableProps<T>) {
  return (
    <table className="sm-table">
      <thead>
        <tr>
          {columns.map((col) => (
            <th key={col.key}>{col.label}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.length === 0 ? (
          <tr>
            <td colSpan={columns.length} className="sm-table__empty">
              {emptyMessage}
            </td>
          </tr>
        ) : (
          rows.map((row, i) => (
            <tr key={rowKey ? rowKey(row) : i}>
              {columns.map((col) => (
                <td key={col.key}>
                  {col.render ? col.render(row) : String((row as Record<string, unknown>)[col.key] ?? "")}
                </td>
              ))}
            </tr>
          ))
        )}
      </tbody>
    </table>
  );
}

// apps/web/src/components/Table.vue
<script setup lang="ts" generic="T">
import "./components.css";

defineProps<{
  columns: { key: string; label: string }[];
  rows: T[];
  emptyMessage?: string;
  rowKey?: (row: T) => string;
}>();
</script>

<template>
  <table class="sm-table">
    <thead>
      <tr>
        <th v-for="col in columns" :key="col.key">{{ col.label }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-if="rows.length === 0">
        <td :colspan="columns.length" class="sm-table__empty">
          {{ emptyMessage ?? "No data." }}
        </td>
      </tr>
      <template v-else>
        <tr v-for="(row, i) in rows" :key="rowKey ? rowKey(row) : i">
          <td v-for="col in columns" :key="col.key">
            <slot :name="`cell-${col.key}`" :row="row">
              {{ String((row as Record<string, unknown>)[col.key] ?? "") }}
            </slot>
          </td>
        </tr>
      </template>
    </tbody>
  </table>
